// CUSTOMER
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const EDIT_CUSTOMER_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
export const FETCH_CUSTOMERS_SUCCESS = "FETCH_CUSTOMERS_SUCCESS";

// OFFICE
export const ADD_OFFICE_SUCCESS = "ADD_OFFICE_SUCCESS";
export const DELETE_OFFICE_SUCCESS = "DELETE_OFFICE_SUCCESS";
export const EDIT_OFFICE_SUCCESS = "EDIT_OFFICE_SUCCESS";
export const FETCH_OFFICES_SUCCESS = "FETCH_OFFICES_SUCCESS";

// OFFICE DEVICES
export const ADD_OFFICE_DEVICE_SUCCESS = "ADD_OFFICE_DEVICE_SUCCESS";
export const DELETE_OFFICE_DEVICE_SUCCESS = "DELETE_OFFICE_DEVICE_SUCCESS";
export const EDIT_OFFICE_DEVICE_SUCCESS = "EDIT_OFFICE_DEVICE_SUCCESS";
export const FETCH_OFFICE_DEVICES_SUCCESS = "FETCH_OFFICE_DEVICES_SUCCESS"; 
export const SELECTED_DEVICE_OFFICE_SET = "SELECTED_DEVICE_OFFICE_SET";

// OFFICE PROPERTIES
export const ADD_PROPERTY_SUCCESS = "ADD_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const EDIT_PROPERTY_SUCCESS = "EDIT_PROPERTY_SUCCESS";
export const FETCH_PROPERTIES_SUCCESS = "FETCH_PROPERTIES_SUCCESS";
export const SELECTED_PROPERTY_OFFICE_SET = "SELECTED_PROPERTY_OFFICE_SET";

// RESERVATIONS
export const ADD_RESERVATION_SUCCESS = "ADD_RESERVATION_SUCCESS";
export const DELETE_RESERVATION_SUCCESS = "DELETE_RESERVATION_SUCCESS";
export const EDIT_RESERVATION_SUCCESS = "EDIT_RESERVATION_SUCCESS";
export const FETCH_RESERVATION_SUCCESS = "FETCH_RESERVATION_SUCCESS";
export const FETCH_RESERVED_DATES_SUCCESS = "FETCH_RESERVED_DATES_SUCCESS";
export const SELECTED_RESERVATION_OFFICE_SET = "SELECTED_RESERVATION_OFFICE";
export const SELECTED_RESERVATION_OFFICE_PROPERTY_SET = "SELECTED_RESERVATION_OFFICE_PROPERTY";
export const SET_AVAILABLE_DEVICES = "SET_AVAILABLE_DEVICES";
export const SET_AVAILABLE_SERVICES = "SET_AVAILABLE_SERVICES";

// OFFICE SERVICES
export const ADD_OFFICE_SERVICE_SUCCESS = "ADD_OFFICE_SERVICE_SUCCESS";
export const DELETE_OFFICE_SERVICE_SUCCESS = "DELETE_OFFICE_SERVICE_SUCCESS";
export const EDIT_OFFICE_SERVICE_SUCCESS = "EDIT_OFFICE_SERVICE_SUCCESS";
export const FETCH_OFFICE_SERVICES_SUCCESS = "FETCH_OFFICE_SERVICES_SUCCESS";
export const SELECTED_SERVICE_OFFICE_SET = "SELECTED_SERVICE_OFFICE_SET";


// UI 
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const HIDE_LOADING = "HIDE_LOADING";
export const SHOW_ERROR = "SHOW_ERROR";
export const SHOW_LOADING = "SHOW_LOADING"
export const SHOW_SUCCESS = "SHOW_SUCCESS"