// CUSTOMER
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const ADD_CUSTOMER_FAILURE = "ADD_CUSTOMER_FAILURE";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_FAILURE";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const EDIT_CUSTOMER = "EDIT_CUSTOMER";
export const EDIT_CUSTOMER_FAILURE = "EDIT_CUSTOMER_FAILURE";
export const EDIT_CUSTOMER_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
export const FETCH_CUSTOMERS = "FETCH_CUSTOMERS"
export const FETCH_CUSTOMERS_SUCCESS = "FETCH_CUSTOMERS_SUCCESS";
export const FETCH_CUSTOMERS_FAILURE = "FETCH_CUSTOMERS_FAILURE";

// OFFICE
export const ADD_OFFICE = "ADD_OFFICE";
export const ADD_OFFICE_FAILURE = "ADD_OFFICE_FAILURE";
export const ADD_OFFICE_SUCCESS = "ADD_OFFICE_SUCCESS";
export const DELETE_OFFICE = "DELETE_OFFICE";
export const DELETE_OFFICE_FAILURE = "DELETE_OFFICE_FAILURE";
export const DELETE_OFFICE_SUCCESS = "DELETE_OFFICE_SUCCESS";
export const EDIT_OFFICE = "EDIT_OFFICE";
export const EDIT_OFFICE_FAILURE = "EDIT_OFFICE_FAILURE";
export const EDIT_OFFICE_SUCCESS = "EDIT_OFFICE_SUCCESS";
export const FETCH_OFFICES = "FETCH_OFFICES";
export const FETCH_OFFICES_FAILURE = "FETCH_OFFICES_FAILURE";
export const FETCH_OFFICES_SUCCESS = "FETCH_OFFICES_SUCCESS";
export const SELECTED_OFFICE_SET = "SELECTED_OFFICE_SET";

// OFFICE PROPERTIES
export const ADD_PROPERTY = "ADD_PROPERTY";
export const ADD_PROPERTY_FAILURE = "ADD_PROPERTY_FAILURE"
export const ADD_PROPERTY_SUCCESS = "ADD_PROPERTY_SUCCESS";
export const DELETE_PROPERTY = "DELETE_PROPERTY";
export const DELETE_PROPERTY_FAILURE = "DELETE_PROPERTY_FAILURE";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const EDIT_PROPERTY = "EDIT_PROPERTY";
export const EDIT_PROPERTY_FAILURE = "EDIT_PROPERTY_FAILURE";
export const EDIT_PROPERTY_SUCCESS = "EDIT_PROPERTY_SUCCESS";
export const FETCH_PROPERTIES = "FETCH_PROPERTIES"
export const FETCH_PROPERTIES_FAILURE = "FETCH_PROPERTIES_FAILURE";
export const FETCH_PROPERTIES_SUCCESS = "FETCH_PROPERTIES_SUCCESS";

// UI 
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const HIDE_LOADING = "HIDE_LOADING";
export const SHOW_ERROR = "SHOW_ERROR";
export const SHOW_LOADING = "SHOW_LOADING"
export const SHOW_SUCCESS = "SHOW_SUCCESS"